apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  # Template for nodes
  template:
    metadata:
      labels:
        nodepool: default
        environment: learning
        managed-by: karpenter

    spec:
      # Reference to EC2NodeClass
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default

      # Requirements for node selection
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]

        - key: kubernetes.io/os
          operator: In
          values: ["linux"]

        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]  # On-demand only

        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["t"]  # T instance family

        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["t3", "t3a"]  # Cost-optimized families

        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: ["medium", "large", "xlarge"]  # Flexible sizing

  # Limits to control maximum resources
  limits:
    cpu: "100"
    memory: "200Gi"

  # Disruption settings for cost optimization
  disruption:
    # Consolidation reduces costs by replacing multiple nodes with fewer, better-fitting nodes
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m

    # Budget controls how many nodes can be disrupted
    budgets:
      - nodes: "10%"  # Allow up to 10% of nodes to be disrupted at once

  # Weight for priority (lower = higher priority)
  weight: 10
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  # AMI selection - use EKS optimized AMI
  amiFamily: AL2023
  amiSelectorTerms:
    - owner: "602401143452"  # AWS EKS AMI account
      name: "amazon-eks-node-al2023-x86_64-standard-1.33-*"

  # IAM role for nodes
  role: "aws-2026-eks-karpenter-node"

  # Subnet selection using Karpenter discovery tag
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "aws-2026-eks"

  # Security group selection using Karpenter discovery tag
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "aws-2026-eks"

  # Block device mappings
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: "20Gi"
        volumeType: gp3
        encrypted: true
        deleteOnTermination: true

  # Metadata options
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required  # IMDSv2 required for security

  # Tags for cost tracking
  tags:
    Name: "karpenter-node"
    Environment: "learning"
    ManagedBy: "Karpenter"
    Project: "aws-2026"
